# Generated by Django 3.2.6 on 2021-10-14 23:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0002_auto_20211006_0217'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardreview',
            name='due_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
