# Generated by Django 3.2.6 on 2021-10-18 23:10

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0003_cardreview_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardreview',
            name='difficulty',
            field=models.SmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='cardreview',
            name='due_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
