# Generated by Django 3.2.6 on 2021-10-19 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0004_auto_20211018_2310'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='description',
            field=models.TextField(default='', max_length=96),
        ),
    ]
