# Generated by Django 3.2.6 on 2021-10-19 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0005_deck_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deck',
            name='description',
            field=models.TextField(default='', max_length=256),
        ),
    ]
